# This is used to run the configuration changes

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.9.2

inputs:
  - name: git-stegeler

outputs:
  - name: config-test-error-files

run:
  path: git-stegeler/ci/scripts/run-config.sh
