# This stage of pipeline is used to test the code

platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine
    tag: latest

inputs:
  - name: git-stegeler

outputs:
  - name: static-test-error-files

run:
  path: git-stegeler/ci/scripts/static-test.sh
