# This stage of pipeline is used to test the code

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.9.2

inputs:
  - name: git-steve

outputs:
  - name: static-error-files

run:
  path: git-steve/ci/scripts/static-test.sh
