# steve's stuff pipline

resources:
  - name: git-stegeler
    type: git
    source:
      uri: https://github.com/stegeler/vmworld2018
      branch: master
      #paths: ['/*']

jobs:
  - name: static-test
    public: true
    plan:
      - get: git-stegeler
        trigger: true
      - task: task-static-test
        file: git-stegeler/ci/tasks/static-test.yml

  - name: run-config
    public: true
    plan:
      - get: git-stegeler
        passed: [static-test]
        trigger: true
      - task: task-run
        file: git-stegeler/ci/tasks/run-config.yml
