# steve's first pipline

resources:
  - name: git-stegeler
    type: git
    source:
      uri: https://github.com/stegeler/vmworld2018
      branch: master

jobs:
  - name: static-test
    public: true
    plan:
      - get: git-stegeler
        trigger: true
      - task: task-static-test
        file: git-stegeler/ci/tasks/static-test.yml

  - name: run-config
    public: true
    plan:
      - get: git-stegeler
        passed: [static-test]
        trigger: true
      - task: task-run
        file: git-stegeler/ci/tasks/run-config.yml
        params:
          VCSA_ADDRESS: ((vcsa_address))
          VCSA_USER: ((vcsa_user))
          VCSA_PASSWORD: ((vcsa_password))
          VCENTER_ADMIN_USER: ((vcenter_admin_user))
          VCENTER_ADMIN_PASSWORD: ((vcenter_admin_password))
